### ISSUE TITLE
Example Code

### ISSUE THREAD

**Issue by hodllabsorg** [Kiyoaki-w/decoder1090-c#1]
Example code runs and exits immediately, any insight?

**Comment by Kiyoaki-w** [comment]
Is the module installed correctly? Or does the code throw any error?

I test the example code in a directory like this. `npm i decoder1090-c`, `node test.js` and it works.
![1](https://user-images.githubusercontent.com/37092142/91701117-6bdf0600-eba9-11ea-824b-f04527d40abb.PNG)
